### ISSUE TITLE
Feature engineering

### ISSUE THREAD

**Issue by abdoulayegk** [Tonyloyt/TanzaniaTourism-Hackathon-2020-Second-place-Winning-Solution#1]
Hi, Tony, I had a look at your solution however, I got most of the part about how you did it but I am a little bit confused about where you combined the train and test dataset.  
Is that a good practice given the fact that they give it separately?
I congrats you for been second in the competition and I wish you all the best.

**Comment by Tonyloyt** [comment]
Hi Abdoulaye,
Thank you, I combined the train and test set to simplify data preprocessing
& data cleaning at once then after data preprocessing i separated as
normal.
The tactic behind that is to fasten the preprocessing of your data.
Thank you.

**Comment by abdoulayegk** [comment]
Thank you for replying I got it.
